# RuboCop設定

# 各公式ドキュメント:
#  RuboCop:             https://docs.rubocop.org/rubocop/
#  RuboCop Capybara:    https://docs.rubocop.org/rubocop-capybara/
#  RuboCop factory_bot: https://docs.rubocop.org/rubocop-factory_bot/
#  RuboCop Performance: https://docs.rubocop.org/rubocop-performance/
#  RuboCop Rails:       https://docs.rubocop.org/rubocop-rails/
#  RuboCop RSpec:       https://docs.rubocop.org/rubocop-rspec/

# Standardの設定値:
#  https://github.com/testdouble/standard/blob/master/config/base.yml

# RuboCopからStandardを利用する方法の参考元:
#   https://github.com/testdouble/standard/issues/135#issuecomment-651198150
#   https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - standard
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable
  SuggestExtensions: true
  Exclude:
    - bin/*
    - db/migrate/*.active_storage.rb
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

inherit_gem:
  standard: config/base.yml

Capybara:
  Enabled: true

FactoryBot:
  Enabled: true

Rails:
  Enabled: true

RSpec:
  Enabled: true

# カスタマイズ

Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: true
  ConsiderPunctuation: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true
  ForceEqualSignAlignment: false

Layout/HashAlignment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - config/initializers/devise.rb
    - config/routes.rb

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Lint/SymbolConversion:
  Enabled: true
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: true
  Max: 20 # デフォルト値は17
  Exclude:
    - db/migrate/**/*

Rails/BulkChangeTable:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/system/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/models/*_translation_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
    - spec/system/**/*

RSpec/NestedGroups:
  Max: 5 # デフォルト値は3

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/RedundantFetchBlock:
  SafeForConstants: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
